In [4]:
import numpy as np

In [63]:
# Defining a seed for replicable randomness
np.random.seed(42)

batch_data = np.round(np.random.normal(loc=[6.4, 5.0, 3.3, 12.0, 0.6],
                                        scale=[1.2, 2.0, 0.3, 1.5, 0.15],
                                        size=[8, 5]), 2)

columns = ["acidity", "sugar", "ph", "alcohol", "sulphates"]

print(f"Batch Data(8 batches x 5 measurements):\n{batch_data}")

print(f"Shape: {batch_data.shape}")

Batch Data(8 batches x 5 measurements):
[[ 7.    4.72  3.49 14.28  0.56]
 [ 6.12  8.16  3.53 11.3   0.68]
 [ 5.84  4.07  3.37  9.13  0.34]
 [ 5.73  2.97  3.39 10.64  0.39]
 [ 8.16  4.55  3.32  9.86  0.52]
 [ 6.53  2.7   3.41 11.1   0.56]
 [ 5.68  8.7   3.3  10.41  0.72]
 [ 4.93  5.42  2.71 10.01  0.63]]
Shape: (8, 5)

In [64]:
# Axis-wise analysis

# Column Analysis
col_mean = batch_data.mean(axis=0)
col_std = batch_data.mean(axis=0)

# Row Analysis
row_mean = batch_data.mean(axis=1)

print(f"Column-wise mean: {dict(zip(columns, np.round(col_mean, 2)))}\n\
        Column-wise std; {dict(zip(columns, np.round(col_std, 2)))}\n\
        Row-wise mean: {np.round(row_mean, 2)}")

Column-wise mean: {'acidity': np.float64(6.25), 'sugar': np.float64(5.16), 'ph': np.float64(3.32), 'alcohol': np.float64(10.84), 'sulphates': np.float64(0.55)}
        Column-wise std; {'acidity': np.float64(6.25), 'sugar': np.float64(5.16), 'ph': np.float64(3.32), 'alcohol': np.float64(10.84), 'sulphates': np.float64(0.55)}
        Row-wise mean: [6.01 5.96 4.55 4.62 5.28 4.86 5.76 4.74]

In [65]:
z_scores= (batch_data - col_mean) / col_std


print(f"Z-score normalized data:\n{np.round(z_scores, 2)}")

print(f"New Colum means: {np.round(z_scores.mean(axis=0), 4)}")
print(f"New Column std: {np.round(z_scores.std(axis=0), 4)}")

Z-score normalized data:
[[ 0.12 -0.09  0.05  0.32  0.02]
 [-0.02  0.58  0.06  0.04  0.24]
 [-0.07 -0.21  0.02 -0.16 -0.38]
 [-0.08 -0.42  0.02 -0.02 -0.29]
 [ 0.31 -0.12  0.   -0.09 -0.05]
 [ 0.05 -0.48  0.03  0.02  0.02]
 [-0.09  0.69 -0.   -0.04  0.31]
 [-0.21  0.05 -0.18 -0.08  0.15]]
New Colum means: [-0.  0. -0. -0. -0.]
New Column std: [0.1477 0.4006 0.0724 0.1341 0.2254]

In [66]:
sulphates = batch_data[: 4]

q1, q3= np.percentile(sulphates, [25, 75])
iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outlier_mask = (sulphates < lower) | (sulphates > upper)

print(f"Q1 = {q1:.3f}, Q3 = {q3:.3f}, IQR = {iqr:.3f}")
print(f"Valid Range: [{lower:.3f}, {upper:.3f}]")
print(f"Values: {sulphates}")
print(f"Outlier mask: {outlier_mask}")
print(f"Outlier batch indices: {np.where(outlier_mask)[0]}")

Q1 = 3.270, Q3 = 7.290, IQR = 4.020
Valid Range: [-2.760, 13.320]
Values: [[ 7.    4.72  3.49 14.28  0.56]
 [ 6.12  8.16  3.53 11.3   0.68]
 [ 5.84  4.07  3.37  9.13  0.34]
 [ 5.73  2.97  3.39 10.64  0.39]]
Outlier mask: [[False False False  True False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
Outlier batch indices: [0]

In [67]:
XtX = batch_data.T @ batch_data
print(f"Shape of X^T X: {XtX.shape}")
print(np.round(XtX, 1))

weights = np.array([0.1, 0.1, 0.2, 0.4, 0.2])
quality_score =  batch_data @ weights
print(f"Weighted score per batch: {np.round(quality_score, 2)}")
print(f"Best batch index: {np.argmax(quality_score)}")

Shape of X^T X: (5, 5)
[[319.2 254.7 166.6 544.8  27.4]
 [254.7 247.3 136.8 448.   24.3]
 [166.6 136.8  88.4 288.6  14.5]
 [544.8 448.  288.6 957.2  48.1]
 [ 27.4  24.3  14.5  48.1   2.5]]
Weighted score per batch: [7.69 6.79 5.38 5.88 5.98 6.16 6.41 5.71]
Best batch index: 0

In [68]:
import pandas as pd

In [69]:
df = pd.read_csv("wine_quality.csv")
print(f"Shape: {df.shape}")
df.head(10)

Shape: (178, 14)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,quality_label
0,12.87,4.61,2.48,21.5,86.0,1.70,0.65,0.47,0.86,7.650000,0.54,1.86,NaN,low
1,13.28,1.64,2.84,15.5,110.0,2.60,2.68,0.34,1.36,4.600000,1.09,2.78,880.0,high
2,12.82,3.37,2.30,19.5,88.0,1.48,0.66,0.40,0.97,10.260000,0.72,1.75,685.0,low
3,12.77,2.39,2.28,19.5,86.0,1.39,0.51,0.48,0.64,9.899999,0.57,1.63,470.0,low
4,12.43,1.53,2.29,21.5,86.0,2.74,3.15,0.39,1.77,3.940000,0.69,2.84,352.0,medium
5,12.70,3.55,2.36,21.5,106.0,1.70,1.20,0.17,0.84,5.000000,0.78,1.29,600.0,low
6,12.34,2.45,2.46,21.0,98.0,2.56,2.11,0.34,1.31,2.800000,0.80,3.38,438.0,medium
7,NaN,1.83,2.36,17.2,104.0,2.42,2.69,0.42,1.97,3.840000,1.23,2.87,990.0,high
8,NaN,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.250000,0.80,3.39,625.0,medium
9,13.62,4.95,2.35,20.0,92.0,2.00,0.80,0.47,1.02,4.400000,0.91,2.05,550.0,low

In [70]:
missing_count = df.isnull().sum()
missing_pct = (df.isnull().mean() * 100).round(2)

missing_report = pd.DataFrame({"Missing Count": missing_count, "Missing Percentage": missing_pct})

missing_report = missing_report[missing_report["Missing Count"] > 0].sort_values("Missing Percentage", ascending=False)

missing_report

                 Missing Count  Missing Percentage
proline                     13                7.30
alcohol                     12                6.74
malic_acid                  12                6.74
color_intensity             10                5.62
magnesium                    5                2.81

In [71]:
df_clean = df.copy()

for col in ["alcohol", "malic_acid", "color_intensity"]:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

df_clean["magnesium"] = df_clean["magnesium"].fillna(df_clean["magnesium"].mean())

df_clean["proline"] = df_clean.groupby("quality_label")["proline"].transform(
    lambda s: s.fillna(s.median())
)

print(f"Missing values remaining: {df_clean.isnull().sum().sum()}")
df_clean[["alcohol", "malic_acid", "magnesium", "color_intensity", "proline"]].describe()

Missing values remaining: 0

          alcohol  malic_acid   magnesium  color_intensity      proline
count  178.000000  178.000000  178.000000       178.000000   178.000000
mean    13.012079    2.315056   99.849711         5.083034   747.820225
std      0.778153    1.099778   14.186030         2.279019   312.530209
min     11.030000    0.740000   70.000000         1.280000   278.000000
25%     12.370000    1.615000   88.000000         3.277500   500.500000
50%     13.050000    1.865000   98.000000         4.800000   660.000000
75%     13.627500    2.982500  107.000000         6.122500  1008.750000
max     14.830000    5.800000  162.000000        13.000000  1680.000000

In [72]:
condition = (
    (df_clean["alcohol"] > df_clean["alcohol"].median())&
    (df_clean["color_intensity"] < df_clean["color_intensity"].median())&
    (~(df_clean["quality_label"] == "low"))
)

filtered = df_clean[condition]
print(f"Matching records:\n{len(filtered)} out of {len(df_clean)}")
filtered[["alcohol", "color_intensity", "quality_label"]].head(10)

Matching records:
12 out of 178

     alcohol  color_intensity quality_label
1      13.28             4.60          high
10     13.71             3.80          high
46     13.87             4.50          high
84     14.02             4.70          high
94     13.24             4.36          high
139    13.86             3.38        medium
143    13.20             4.38          high
148    13.24             4.32          high
149    13.07             3.70          high
151    13.51             4.20          high

In [73]:
numeric_df = df_clean.drop(columns=["quality_label"])
corr_mat = numeric_df.corr()

flavanoid_corr = corr_mat["flavanoids"].drop("flavanoids").sort_values(key=abs, ascending=False)

print(f"Top Correlations with flavaniods:")
flavanoid_corr.head(5)

Top Correlations with flavaniods:

total_phenols                   0.864564
od280/od315_of_diluted_wines    0.787194
proanthocyanins                 0.652692
hue                             0.543479
nonflavanoid_phenols           -0.537900
Name: flavanoids, dtype: float64

In [74]:
from sklearn.datasets import load_wine

In [75]:
wine = load_wine()
X, y = wine.data, wine.target

print(f"Feature matrix shape: {X.shape}")
print(f"Target vector shape: {y.shape}")
print(f"Classes: ", *wine.target_names)
print(f"Class distributions: {dict(zip(*np.unique(y, return_counts=True)))}")

Feature matrix shape: (178, 13)
Target vector shape: (178,)
Classes:  class_0 class_1 class_2
Class distributions: {np.int64(0): np.int64(59), np.int64(1): np.int64(71), np.int64(2): np.int64(48)}

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

print(f"Train size: {X_train.shape[0]} | Test size: {X_test.shape[0]}")
print(f"Train class distribution: {dict(zip(*np.unique(y_train, return_counts=True)))}")
print(f"Test class distribution: {dict(zip(*np.unique(y_test, return_counts=True)))}")

Train size: 142 | Test size: 36
Train class distribution: {np.int64(0): np.int64(47), np.int64(1): np.int64(57), np.int64(2): np.int64(38)}
Test class distribution: {np.int64(0): np.int64(12), np.int64(1): np.int64(14), np.int64(2): np.int64(10)}

In [78]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [81]:
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Train mean after scaling (expedcted: ~0): ", *np.round(X_train_scaled.mean(axis=0), 3))

print(f"Test mean after scaling (expedcted: not exactly ezero): ", *np.round(X_test_scaled.mean(axis=0), 3))

Train mean after scaling (expedcted: ~0):  0.0 -0.0 0.0 0.0 0.0 -0.0 0.0 -0.0 -0.0 0.0 -0.0 0.0 -0.0
Test mean after scaling (expedcted: not exactly ezero):  0.18 -0.016 0.031 -0.191 0.036 0.171 0.229 0.071 -0.08 0.145 0.185 0.039 0.122